sudo: required
dist: trusty

language: cpp

git:
    depth: 1

before_install:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update --fix-missing
    - sudo apt-get install -qq
        clang
        libfreetype6-dev
        libx11-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - pwd
    - ls -d */
    - cd ..
    - pwd
    - git clone --depth=1 --branch=master https://github.com/julianstorer/juce.git JUCE
    - pwd
    - ls -d */

compiler:
    - clang

branches:
    only:
        - master

script:
    - ls
    - make -C "Chataigne/Builds/LinuxMakefile/" 